import { Link } from "@tanstack/react-router";
import { CheckoutLink } from "./CheckoutLink";

export type Benefit = { title: string; body: string };
export interface ModuleSalesConfig {
  moduleName:string; logo:string; metaTitle:string; metaDescription:string; eyebrow:string; headline:string; subhead:string;
  ctaPrimary:string; ctaPrimaryPrice:string; ctaSecondary:string; primaryHref:string; primaryButton:string; yearlyHref:string; yearlyButton:string;
  monthlyPrice:string; yearlyPrice:string; yearlyBadge?:string; yearlyApx?:string; monthlyBlurb:string; yearlyBlurb:string; cardLine:string;
  benefitsHeading:string; benefits:Benefit[]; featuresHeading:string; features:string[]; priceNote?:string; startNoteTitle:string; startNoteBody:string;
  footerLink?:{to:string;label:string}; heroMicrocopy?:string; resourceLinks?:{to:string;label:string}[];
}
export function ModuleSalesPage(config:ModuleSalesConfig){return <main className="flex min-h-screen flex-col bg-gray-950 text-white">
<header className="flex items-center justify-between border-b border-gray-800/50 px-4 py-4 sm:px-6"><Link to="/" className="flex items-center gap-2 text-lg font-semibold transition hover:text-indigo-400"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-indigo-600 text-lg">{config.logo}</span>DocSnap</Link><nav className="flex items-center gap-4 text-sm text-gray-400"><Link to="/resources" className="hover:text-gray-200">Resources</Link><Link to="/pricing" className="hover:text-gray-200">Pricing</Link></nav></header>
<section className="border-b border-gray-800/50 px-4 py-16 sm:px-6 sm:py-24"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-medium text-indigo-400">{config.eyebrow} · a DocSnap module</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">{config.headline}</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-gray-300">{config.subhead}</p><div className="mt-8"><CheckoutLink href={config.primaryHref} className="inline-flex justify-center rounded-full bg-indigo-600 px-8 py-3.5 text-base font-semibold transition hover:bg-indigo-500">{config.ctaPrimary} — {config.ctaPrimaryPrice}</CheckoutLink><p className="mt-3 text-sm text-gray-400">{config.ctaSecondary}</p></div><p className="mt-5 text-xs text-gray-500">{config.heroMicrocopy??"Inside your DocSnap account. Cancel anytime. No credit card required to browse."}</p></div></section>
<section className="border-b border-gray-800/50 px-4 py-16 sm:px-6"><div className="mx-auto max-w-3xl"><h2 className="text-center text-2xl font-bold sm:text-3xl">{config.benefitsHeading}</h2><div className="mt-10 space-y-8">{config.benefits.map(b=><div key={b.title} className="rounded-2xl border border-gray-800 bg-gray-900/60 p-6 sm:p-8"><h3 className="text-xl font-semibold">{b.title}</h3><p className="mt-3 leading-relaxed text-gray-300">{b.body}</p></div>)}</div></div></section>
<section className="border-b border-gray-800/50 px-4 py-16 sm:px-6"><div className="mx-auto max-w-3xl"><h2 className="text-center text-2xl font-bold sm:text-3xl">{config.featuresHeading}</h2><ul className="mt-8 space-y-3">{config.features.map(f=><li key={f} className="flex items-start gap-3 text-sm leading-relaxed text-gray-300"><span className="text-indigo-400">✓</span><span>{f}</span></li>)}</ul></div></section>
{config.resourceLinks?.length?<section className="border-b border-gray-800/50 px-4 py-12 sm:px-6"><div className="mx-auto max-w-3xl"><p className="text-xs font-semibold uppercase tracking-wider text-indigo-400">Learn before you buy</p><h2 className="mt-2 text-2xl font-bold">Related DocSnap guides</h2><div className="mt-5 flex flex-wrap gap-3">{config.resourceLinks.map(r=><Link key={r.to} to={r.to as "/"} className="rounded-xl border border-gray-700 px-4 py-3 text-sm font-semibold text-gray-200 transition hover:border-indigo-500 hover:text-white">{r.label} →</Link>)}</div></div></section>:null}
<section className="border-b border-gray-800/50 px-4 py-16 sm:px-6"><div className="mx-auto max-w-3xl"><h2 className="text-center text-2xl font-bold sm:text-3xl">Simple, honest pricing</h2><div className="mt-8 grid gap-5 sm:grid-cols-2"><div className="flex flex-col rounded-2xl border border-gray-800 bg-gray-900/60 p-6"><p className="text-sm text-gray-400">Monthly</p><p className="mt-3 text-4xl font-bold">{config.monthlyPrice}<span className="text-base font-normal text-gray-400">/month</span></p><p className="mt-3 text-sm text-gray-400">{config.monthlyBlurb}</p><p className="mt-1 text-sm text-gray-300">{config.cardLine}</p><CheckoutLink href={config.primaryHref} className="mt-6 rounded-full bg-indigo-600 px-6 py-3 text-center text-sm font-semibold">{config.primaryButton}</CheckoutLink></div><div className="flex flex-col rounded-2xl border border-indigo-700/60 bg-indigo-950/30 p-6"><div className="flex justify-between"><p className="text-sm text-indigo-300">Yearly · Best value</p>{config.yearlyBadge&&<span className="rounded-full bg-indigo-600/20 px-2.5 py-1 text-xs text-indigo-200">{config.yearlyBadge}</span>}</div><p className="mt-3 text-4xl font-bold">{config.yearlyPrice}<span className="text-base font-normal text-gray-400">/year</span></p><p className="mt-2 text-xs text-gray-500">{config.yearlyApx}</p><p className="mt-2 text-sm text-gray-400">{config.yearlyBlurb}</p><p className="mt-1 text-sm text-gray-300">{config.cardLine}</p><CheckoutLink href={config.yearlyHref} className="mt-6 rounded-full border border-indigo-500 px-6 py-3 text-center text-sm font-semibold text-indigo-200">{config.yearlyButton}</CheckoutLink></div></div><p className="mt-6 text-center text-sm text-gray-400">{config.priceNote??<>One {config.moduleName.toLowerCase()} record, all your data, on one price. <span className="text-gray-500">Cancel anytime.</span></>}</p></div></section>
<section className="px-4 py-16 sm:px-6"><div className="mx-auto max-w-2xl text-center"><CheckoutLink href={config.primaryHref} className="inline-flex rounded-full bg-indigo-600 px-8 py-3.5 text-base font-semibold">{config.primaryButton}</CheckoutLink><p className="mt-3 text-sm text-gray-400">Yearly option — {config.yearlyPrice}/year</p><div className="mx-auto mt-8 max-w-xl rounded-xl border border-gray-800 bg-gray-900/50 p-5 text-left text-sm leading-relaxed text-gray-300"><strong className="text-gray-100">{config.startNoteTitle}</strong> {config.startNoteBody}</div>{config.footerLink&&<div className="mt-8"><Link to={config.footerLink.to as "/"} className="text-sm text-indigo-400">{config.footerLink.label} →</Link></div>}</div></section>
<footer className="flex flex-wrap items-center justify-center gap-6 border-t border-gray-800/50 py-5 text-xs text-gray-500"><Link to="/resources">Resources</Link><Link to="/pricing">Pricing</Link><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><Link to="/contact">Contact</Link></footer></main>;}